# Generated by Django 4.0.1 on 2022-01-12 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('profession', models.CharField(max_length=255, verbose_name='profession')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='service_name')),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
                ('time', models.CharField(default='24/7', max_length=20, verbose_name='time')),
                ('doctor', models.ManyToManyField(related_name='doctor', to='first.Doctor', verbose_name='doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='service', to='first.Service', verbose_name='service'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='mail')),
                ('date', models.CharField(max_length=255, verbose_name='date')),
                ('time', models.CharField(max_length=255, verbose_name='time')),
                ('acceptance', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.doctor', verbose_name='doctor')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.service', verbose_name='service')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
