# Generated by Django 4.0.1 on 2022-01-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='special',
            field=models.CharField(choices=[(1, 'Ортопед'), (2, 'Ортодонт'), (3, 'Детский-врач'), (4, 'Терапевт'), (5, 'Хирург')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
