# Generated by Django 4.0.1 on 2022-01-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='service', to='first.Service', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image'),
        ),
    ]
