# Generated by Django 4.0.1 on 2022-01-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_alter_doctor_img_alter_doctor_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='email',
            new_name='mail',
        ),
    ]
