# Generated by Django 4.0.1 on 2022-01-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_alter_appointment_doctor_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=25, verbose_name='description'),
        ),
    ]
