# Generated by Django 4.0.1 on 2022-01-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_alter_service_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='service',
            name='description2',
            field=models.CharField(default=1, max_length=25, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='description3',
            field=models.CharField(default=1, max_length=25, verbose_name='description'),
            preserve_default=False,
        ),
    ]
