# Generated by Django 4.0.1 on 2022-01-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_rename_description_service_description1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(blank=True, choices=[('otbelivanie', 'otbelivanie'), ('Chistka', 'Chistka'), ('karies', 'karies'), ('brevity', 'brevity')], max_length=255, null=True, verbose_name='service'),
        ),
    ]
