# Generated by Django 4.0.1 on 2022-01-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_alter_appointment_doctor_alter_appointment_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('comment', models.TextField(verbose_name='comment')),
                ('img', models.IntegerField(verbose_name='img')),
            ],
        ),
    ]
