# Generated by Django 4.0.1 on 2022-01-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='img'),
        ),
    ]
