# Generated by Django 4.0.1 on 2022-01-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_remove_appointment_mail_appointment_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
    ]
